version: "3"
services:
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5682:5672"
      - "15682:15672"
    networks:
      - "platibus-unit-tests"

  mongo:
    image: mongo:3.6.0-jessie
    ports:
      - "27027:27017"
    networks:
      - "platibus-unit-tests"
  
  influxdb:
    image: influxdb
    ports:
      - "8093:8083"
      - "8096:8086"
    networks:
      - "platibus-unit-tests"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    ports:
      - "9210:9200"
      - "9310:9300"
    environment:
      - http.host=0.0.0.0
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - "platibus-unit-tests"

  graylog:
    image: graylog/graylog:2.3.2-1
    links:
      - mongo
      - elasticsearch
    ports:
      - "9010:9000"
      - "12211:12201"
      - "12211:12201/udp"
    networks:
      - "platibus-unit-tests"

networks:
  platibus-unit-tests: